sudo: required
services:
    - docker
before_install:
    - docker build -t lcruzero/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run lcruzero/react-test npm test -- --coverage
after_success:
    - docker build -t lcruzero/multi-client ./client
    - docker build -t lcruzero/multi-nginx ./nginx
    - docker build -t lcruzero/multi-server ./server
    - docker built -t lcruzero/multi-worker ./worker 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
    - docker push lcruzero/multi-client
    - docker push lcruzero/multi-nginx
    - docker push lcruzero/multi-server
    - docker push lcruzero/multi-worker 
