sudo: required

services:
    - docker
      #add test
before_install:
    - docker build -t lcruzero/react-test -f ./client/Dockerfile.dev ./client
    #run fail safe test
script:
    - docker run lcruzero/react-test npm test -- --coverage
      #build images with tags
after_success:
    - docker build -t lcruzero/multi-client ./client
    - docker build -t lcruzero/multi-nginx ./nginx
    - docker build -t lcruzero/multi-server ./server
    - docker build -t lcruzero/multi-worker ./worker 
      # log into docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      # push images to docker hub
    - docker push lcruzero/multi-client
    - docker push lcruzero/multi-nginx
    - docker push lcruzero/multi-server
    - docker push lcruzero/multi-worker 
